/**
 * LLM-003: Tool description should explain WHAT the tool does
 *
 * Validates that the description contains action verbs that explain
 * the tool's functionality to the LLM.
 */

import type { Rule } from '../types.js';
import type { ValidationIssue } from '../../types/index.js';

// Common action verbs that indicate what a tool does
const ACTION_VERBS = [
  'create', 'creates', 'creating',
  'read', 'reads', 'reading',
  'update', 'updates', 'updating',
  'delete', 'deletes', 'deleting',
  'get', 'gets', 'getting',
  'set', 'sets', 'setting',
  'list', 'lists', 'listing',
  'search', 'searches', 'searching',
  'find', 'finds', 'finding',
  'fetch', 'fetches', 'fetching',
  'retrieve', 'retrieves', 'retrieving',
  'send', 'sends', 'sending',
  'submit', 'submits', 'submitting',
  'execute', 'executes', 'executing',
  'run', 'runs', 'running',
  'process', 'processes', 'processing',
  'generate', 'generates', 'generating',
  'convert', 'converts', 'converting',
  'transform', 'transforms', 'transforming',
  'validate', 'validates', 'validating',
  'check', 'checks', 'checking',
  'verify', 'verifies', 'verifying',
  'analyze', 'analyzes', 'analyzing',
  'calculate', 'calculates', 'calculating',
  'compute', 'computes', 'computing',
  'download', 'downloads', 'downloading',
  'upload', 'uploads', 'uploading',
  'import', 'imports', 'importing',
  'export', 'exports', 'exporting',
  'connect', 'connects', 'connecting',
  'disconnect', 'disconnects', 'disconnecting',
  'start', 'starts', 'starting',
  'stop', 'stops', 'stopping',
  'enable', 'enables', 'enabling',
  'disable', 'disables', 'disabling',
  'configure', 'configures', 'configuring',
  'initialize', 'initializes', 'initializing',
  'query', 'queries', 'querying',
  'filter', 'filters', 'filtering',
  'sort', 'sorts', 'sorting',
  'merge', 'merges', 'merging',
  'split', 'splits', 'splitting',
  'extract', 'extracts', 'extracting',
  'parse', 'parses', 'parsing',
  'format', 'formats', 'formatting',
  'render', 'renders', 'rendering',
  'display', 'displays', 'displaying',
  'show', 'shows', 'showing',
  'hide', 'hides', 'hiding',
  'open', 'opens', 'opening',
  'close', 'closes', 'closing',
  'save', 'saves', 'saving',
  'load', 'loads', 'loading',
  'store', 'stores', 'storing',
  'remove', 'removes', 'removing',
  'add', 'adds', 'adding',
  'insert', 'inserts', 'inserting',
  'append', 'appends', 'appending',
  'prepend', 'prepends', 'prepending',
  'copy', 'copies', 'copying',
  'move', 'moves', 'moving',
  'rename', 'renames', 'renaming',
  'authenticate', 'authenticates', 'authenticating',
  'authorize', 'authorizes', 'authorizing',
  'encrypt', 'encrypts', 'encrypting',
  'decrypt', 'decrypts', 'decrypting',
  'compress', 'compresses', 'compressing',
  'decompress', 'decompresses', 'decompressing',
  'install', 'installs', 'installing',
  'uninstall', 'uninstalls', 'uninstalling',
  'deploy', 'deploys', 'deploying',
  'build', 'builds', 'building',
  'compile', 'compiles', 'compiling',
  'test', 'tests', 'testing',
  'debug', 'debugs', 'debugging',
  'monitor', 'monitors', 'monitoring',
  'track', 'tracks', 'tracking',
  'log', 'logs', 'logging',
  'record', 'records', 'recording',
  'measure', 'measures', 'measuring',
  'count', 'counts', 'counting',
  'sum', 'sums', 'summing',
  'average', 'averages', 'averaging',
  'aggregate', 'aggregates', 'aggregating',
  'group', 'groups', 'grouping',
  'join', 'joins', 'joining',
  'link', 'links', 'linking',
  'unlink', 'unlinks', 'unlinking',
  'attach', 'attaches', 'attaching',
  'detach', 'detaches', 'detaching',
  'sync', 'syncs', 'syncing',
  'synchronize', 'synchronizes', 'synchronizing',
  'refresh', 'refreshes', 'refreshing',
  'reload', 'reloads', 'reloading',
  'reset', 'resets', 'resetting',
  'clear', 'clears', 'clearing',
  'clean', 'cleans', 'cleaning',
  'purge', 'purges', 'purging',
  'backup', 'backups', 'backing',
  'restore', 'restores', 'restoring',
  'recover', 'recovers', 'recovering',
  'publish', 'publishes', 'publishing',
  'unpublish', 'unpublishes', 'unpublishing',
  'schedule', 'schedules', 'scheduling',
  'cancel', 'cancels', 'cancelling',
  'approve', 'approves', 'approving',
  'reject', 'rejects', 'rejecting',
  'accept', 'accepts', 'accepting',
  'decline', 'declines', 'declining',
  'notify', 'notifies', 'notifying',
  'alert', 'alerts', 'alerting',
  'warn', 'warns', 'warning',
  'report', 'reports', 'reporting',
  'summarize', 'summarizes', 'summarizing',
  'describe', 'describes', 'describing',
  'explain', 'explains', 'explaining',
  'provide', 'provides', 'providing',
  'return', 'returns', 'returning',
  'yield', 'yields', 'yielding',
  'emit', 'emits', 'emitting',
  'broadcast', 'broadcasts', 'broadcasting',
  'stream', 'streams', 'streaming',
  'pipe', 'pipes', 'piping',
  'route', 'routes', 'routing',
  'redirect', 'redirects', 'redirecting',
  'forward', 'forwards', 'forwarding',
  'proxy', 'proxies', 'proxying',
  'wrap', 'wraps', 'wrapping',
  'unwrap', 'unwraps', 'unwrapping',
  'encode', 'encodes', 'encoding',
  'decode', 'decodes', 'decoding',
  'serialize', 'serializes', 'serializing',
  'deserialize', 'deserializes', 'deserializing',
  'map', 'maps', 'mapping',
  'reduce', 'reduces', 'reducing',
  'flatten', 'flattens', 'flattening',
  'normalize', 'normalizes', 'normalizing',
  'sanitize', 'sanitizes', 'sanitizing',
  'escape', 'escapes', 'escaping',
  'unescape', 'unescapes', 'unescaping',
  'trim', 'trims', 'trimming',
  'pad', 'pads', 'padding',
  'truncate', 'truncates', 'truncating',
  'expand', 'expands', 'expanding',
  'collapse', 'collapses', 'collapsing',
  'invoke', 'invokes', 'invoking',
  'call', 'calls', 'calling',
  'trigger', 'triggers', 'triggering',
  'fire', 'fires', 'firing',
  'raise', 'raises', 'raising',
  'throw', 'throws', 'throwing',
  'catch', 'catches', 'catching',
  'handle', 'handles', 'handling',
  'manage', 'manages', 'managing',
  'control', 'controls', 'controlling',
  'coordinate', 'coordinates', 'coordinating',
  'orchestrate', 'orchestrates', 'orchestrating',
  'write', 'writes', 'writing',
  'modify', 'modifies', 'modifying',
];

const rule: Rule = {
  id: 'LLM-003',
  category: 'llm-compatibility',
  defaultSeverity: 'warning',
  description: 'Tool description should explain WHAT the tool does',

  check(tool, _ctx) {
    const issues: ValidationIssue[] = [];

    // Skip if description is empty (handled by LLM-001)
    if (!tool.description || tool.description.trim() === '') {
      return issues;
    }

    const descLower = tool.description.toLowerCase();
    const hasActionVerb = ACTION_VERBS.some(verb => {
      // Match word boundaries to avoid partial matches
      const regex = new RegExp(`\\b${verb}\\b`, 'i');
      return regex.test(descLower);
    });

    if (!hasActionVerb) {
      issues.push({
        id: this.id,
        category: this.category,
        severity: this.defaultSeverity,
        message: 'Tool description does not clearly explain what the tool does',
        tool: tool.name,
        path: 'description',
        suggestion: 'Start the description with an action verb (e.g., "Creates...", "Retrieves...", "Sends...")',
      });
    }

    return issues;
  },
};

export default rule;
